trigger:
  branches:
    include:
      - main

variables:
  # Pipeline configuration
  AZURE_SUBSCRIPTION: "Azure-Subscription-Trading"
  POOL_NAME: "TradingContainerAgent"

  # Docker / ACR
  ACR_NAME: "tradingacr"
  IMAGE_NAME: "tradingapp"
  IMAGE_TAG: "$(Build.BuildId)"

  # AKS Kubernetes
  AKS_RESOURCE_GROUP: "TradingInfra"
  AKS_CLUSTER_NAME: "TradingCluster"
  KUBE_NAMESPACE: "tradingapp"
  MANIFEST_FOLDER: "kubernetes"

stages:
- stage: BuildImage
  displayName: Build TradingApp Container Image
  jobs:
  - job: Build
    displayName: ACR Build
    pool:
      name: $(POOL_NAME)
    steps:
    - task: AzureCLI@2
      displayName: Build image in ACR
      inputs:
        azureSubscription: $(AZURE_SUBSCRIPTION)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az acr build --registry tradingacr --image tradingapp:latest Go

- stage: DeployTradingApp
  displayName: "Deploy TradingApp to AKS"
  dependsOn: BuildAndPushImage
  jobs:
  - job: Deploy
    displayName: "Deploy Kubernetes resources"
    pool:
      name: $(POOL_NAME)
    steps:
    - task: AzureCLI@2
      displayName: "Set up kubeconfig for AKS"
      inputs:
        azureSubscription: $(AZURE_SUBSCRIPTION)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az aks get-credentials \
            --resource-group $(AKS_RESOURCE_GROUP) \
            --name $(AKS_CLUSTER_NAME) \
            --overwrite-existing

    - script: |
        kubectl create namespace $(KUBE_NAMESPACE) --dry-run=client -o yaml | kubectl apply -f -
      displayName: "Ensure Kubernetes namespace exists"


    - script: |
        kubectl apply -f $(MANIFEST_FOLDER)
      displayName: "Deploy all Kubernetes YAML manifests"