trigger:
  branches:
    include:
      - main

variables:
  # Pipeline configuration
  AZURE_SUBSCRIPTION: "Azure-Subscription-Trading"
  POOL_NAME: "TradingContainerAgent"

  # ACR
  ACR_NAME: "kubetrading"
  IMAGE_NAME: "tradingapp"
  TAG: "latest"
  TRADING_APP_IMAGE: "$(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(TAG)"

  # AKS Kubernetes
  AKS_RESOURCE_GROUP: "TradingInfra"
  AKS_CLUSTER_NAME: "TradingCluster"
  KUBE_NAMESPACE: "tradingapp"
  MANIFEST_FOLDER: "kubernetes/TradingAppDeploy"
  
stages:
- stage: BuildImage
  displayName: Build TradingApp Container Image
  jobs:
  - job: Build
    displayName: ACR Build
    pool:
      name: $(POOL_NAME)
    steps:
    - task: AzureCLI@2
      displayName: Build image in ACR
      inputs:
        azureSubscription: $(AZURE_SUBSCRIPTION)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az acr build --registry $(ACR_NAME) --image $(IMAGE_NAME):$(TAG) Go

- stage: DeployTradingApp
  displayName: "Deploy TradingApp to AKS"
  dependsOn: BuildImage
  jobs:
  - job: Deploy
    displayName: "Deploy Kubernetes resources"
    pool:
      name: $(POOL_NAME)
    steps:
    - task: AzureCLI@2
      displayName: "Set up kubeconfig for AKS"
      inputs:
        azureSubscription: $(AZURE_SUBSCRIPTION)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az aks get-credentials \
            --resource-group $(AKS_RESOURCE_GROUP) \
            --name $(AKS_CLUSTER_NAME) \
            --overwrite-existing

    - script: |
        kubectl create namespace $(KUBE_NAMESPACE) --dry-run=client -o yaml | kubectl apply -f -
      displayName: "Creat Kubernetes namespace if it doesn't already exist"

    - script: |
        kubectl create secret generic alpaca-secrets \
          --namespace $(KUBE_NAMESPACE) \
          --from-literal=APCA_API_KEY_ID=$APCA_API_KEY_ID \
          --from-literal=APCA_API_SECRET_KEY=$APCA_API_SECRET_KEY \
          --dry-run=client -o yaml | kubectl apply -f -
      displayName: "Create Alpaca Secret"

    - script: |
        export TRADING_APP_IMAGE=$(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(TAG)
        for f in $(MANIFEST_FOLDER)/*.yaml; do
            sed -i "s|\${TRADING_APP_IMAGE}|$TRADING_APP_IMAGE|g" "$f"
            kubectl apply -f "$f" -n $(KUBE_NAMESPACE)
        done
      displayName: "Deploy TradingApp with dynamic image"