apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trading-app
  template:
    metadata:
      labels:
        app: trading-app
    spec:
      containers:
        - name: trading-app
          image: ${TRADING_APP_IMAGE}
          imagePullPolicy: Always
          env:
            - name: ALPACA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: alpaca-secrets
                  key: ALPACA_API_KEY

            - name: ALPACA_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: alpaca-secrets
                  key: ALPACA_API_SECRET

            - name: ALPACA_BASE_URL
              value: "https://paper-api.alpaca.markets"