---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elastic
spec:
  version: 8.16.0
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
      podTemplate:
        spec:
          volumes:
            - name: elasticsearch-data
              emptyDir: {}
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 50Gi
            storageClassName: default

---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic
spec:
  version: 8.16.0
  count: 1

  elasticsearchRef:
    name: elasticsearch

  config:
    xpack.fleet.enabled: true
    xpack.fleet.agents.fleet_server.hosts:
      - http://kibana-kb-http.elastic.svc:5601
    xpack.fleet.agents.elasticsearch.hosts:
      - https://elasticsearch-es-http.elastic.svc:9200

---
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: fleetserver
  namespace: elastic
spec:
  version: 8.16.0
  mode: fleet
  fleetServerEnabled: true
  
  elasticsearchRefs:
    - name: elasticsearch
      namespace: elastic
  kibanaRef:
    name: kibana
    namespace: elastic
  deployment:
    replicas: 1